# Generated by Django 6.0.4 on 2026-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'In Progress'), ('Completed', 'Completed'), ('Late', 'Late')], default='In-Progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'In Progress'), ('Completed', 'Completed'), ('Late', 'Late')], default='In-Progress', max_length=11),
        ),
    ]
